### ISSUE TITLE
What to do once the M3N@ E31HA is flashed?

### ISSUE THREAD

**Issue by obones** [dustybee/HanshowESL#5]
Hello,

I have been playing with a donated M3N@ E31HA display and first noticed the project from @atc1441 where you mentioned your specific firmware for E31HA here: https://github.com/atc1441/ATC_TLSR_Paper/issues/1#issuecomment-1028213718

I thus used the OTA flasher via my mobile phone to upload the zip file content, but I can't figure out what to do next.
The image has not changed on the display itself, and if I revert to the firmware sent via serial adapter, it doesn't change either, just a black rectangle that blinks around the existing content.

I must have been doing something wrong, but I'm not sure what.

**Comment by dustybee** [comment]
Hi,

My version of the firmware is just to show it can work with that model because it didn't at first. My version only displays a static image. it doesn't work with the image upload and OTA flasher like the firmware from atc1441. I haven't done anything with the epaper tags since last year.

Did the tag work with the atc1441 firmware flashed via serial adapter before?

**Comment by obones** [comment]
>Did the tag work with the atc1441 firmware flashed via serial adapter before?
Well, kind of.
It flashes the LED while writing, and after it has been rebooted, the image is "slightly" modified with a blinking black rectangle around it.
I believe this comes from an inappropriate image sent to the display, but I'm a bit too "fresh" on that subject to be sure

**Comment by dustybee** [comment]
Did you first unlock the flash of the tag? I think in the later versions of atc1441's firmware one of the LED's should start blinking to show it is looking for a bluetooth device to connect to. If the firmware is working it should at least do that.

**Comment by obones** [comment]
I believe I did, but I'll recheck.
In any case, thanks for your help, I'll bring the discussion over at atc1441's
