### ISSUE TITLE
RF Protocol

### ISSUE THREAD

**Issue by kizlol** [dustybee/HanshowESL#6]
Hi dustybee,

Woud you mind sharing how you got the RF protocol frames structures ? 
Was it by reverse engineering of the firmware or only by observation with your HackRF ?

Thanks.

**Comment by dustybee** [comment]
Hi,

I found some firmware on GitHub for a USB dongle supporting the Hanshow labels. I found multiple, but after looking at the heartbeats I found the right one. I don't remember which one it is and where I found it exactly. I did download it but I am not near a computer right now. Are you looking for something specific?

**Comment by kizlol** [comment]
Nothing specific, i'm curious and I would like to explore how the label works with its original firmware.

I'd be interested to check it out if you still have it. 
Thanks !

**Comment by dustybee** [comment]
Hi,

I think this is the zip download of the GitHub project I mentioned.
[TI-platform-master.zip](https://github.com/dustybee/HanshowESL/files/13189417/TI-platform-master.zip)

If you find anything interesting, could you share it? Thanks :)

**Comment by kizlol** [comment]
Sure.
Thanks again.
